button_config:
  BUTTON_PIN: 17
  RST_BUTTON_PIN: 27

recorder_config:
  RECORDING_PATH: recordings
  SFX_PATH: sfx
  BEEP_FILE: beep.wav


  ARECORD_CMD: 
    - "arecord"
    - "-f"
    - "cd"  # Record in CD quality (16-bit little endian, 44100 Hz, Stereo)
    - "-t"
    - "wav"  # Save as WAV file type
    - "-D"
    - "plughw:2,0" # find from 'arecord -l'

player_config:
  APLAY_CMD:
    - "aplay"
    - "-D"
    - "plughw:2,0" # Use default output device

led_config:
# if no led is implemented in the device, leave the values blank or change them to None
  DATA_PIN: "D18" #only following pins (GPIO number) allowed: D10, D12, D18 or D21
  PIXEL_NUM: 1