button_config:
  BUTTON_PIN: 22
  RST_BUTTON_PIN: 27

recorder_config:
  RECORDING_PATH: recordings2
  SFX_PATH: sfx
  BEEP_FILE: beep.wav


  ARECORD_CMD: 
    - "arecord"
    - "-f"
    - "cd"  # Record in CD quality (16-bit little endian, 44100 Hz, Stereo)
    - "-t"
    - "wav"  # Save as WAV file type
    - "-D"
    - "plughw:3,0" # find from 'arecord -l'
    - "-d"
    - "20" # limit to 20 seconds per recording

player_config:
  APLAY_CMD:
    - "aplay"
    - "-D"
    - "plughw:3,0" # Use default output device
  VOICE_PATH: voice
  QUESTION: leiwand.wav

led_config:
# if no led is implemented in the device, leave the values blank or change them to None
  DATA_PIN: #only following pins (GPIO number) allowed: D10, D12, D18 or D21
  PIXEL_NUM:
