button_config:
  BUTTON_PIN: 17
  RST_BUTTON_PIN: 27

recording_config:
  RECORDING_PATH: recordings
  SFX_PATH: sfx
  BEEP_FILE: beep.wav


  ARECORD_CMD: 
    - "arecord"
    - "-f"
    - "cd"  # Record in CD quality (16-bit little endian, 44100 Hz, Stereo)
    - "-t"
    - "wav"  # Save as WAV file type
    - "-D"
    - "plughw:2,0" # find from 'arecord -l'

  APLAY_CMD:
    - "aplay"
    - "-D"
    - "plughw:2,0" # Use default output device
