from typing import Protocol

# Just for typehint & pylance (highlighting)
# mathing all function calls & params of CmdRegistry defined in Main
class CmdTyping(Protocol):

    def reset_recordings(self) -> None: ...
    def start_recording(self) -> None: ...

    def stop_recording(self) -> None: ...
    def play_sound(self, filename) -> None: ...
    def get_rec_buffer(self) -> list: ...
    
    def pause_player(self) -> None: ...
    def resume_player(self) -> None: ...
    def skip_player(self) -> None: ...
