from typing import Protocol

# Just for typehint & pylance (highlighting)
class CmdTyping(Protocol):

    def reset_recordings(self) -> None: ...
    def start_recording(self) -> None: ...
    def skip_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def play_sound(self, filename) -> None: ...
